name: iot-example-graphical-snap  # you probably want to 'snapcraft register <name>'
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: IoT example using Qt # 79 char long summary
description: IoT example using Qt
confinement: strict
compression: lzo
grade: stable
base: core26

apps:
  iot-example-graphical-snap:
    command-chain: &_command-chain
      - bin/gpu-2604-wrapper
      - bin/wayland-launch
      - bin/dbus-launch
    command: &_command usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt5/examples/widgets/widgets/calculator/calculator
    plugs: &_plugs
      - opengl
      - wayland
      - audio-playback
      - network-bind
    environment: &_environment
      # These environment variables are typically needed by Qt applications to ensue the snapped version of
      # Qt components are found and used
      QT_QPA_PLATFORM: wayland
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt5/plugins/
      QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt5/plugins/platforms/
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt5/qml

  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command-chain: *_command-chain
    command: *_command
    plugs: *_plugs
    environment: *_environment

# This is one of four snippets that relate to providing the userspace graphics needed by your application.
# You can treat this as "magic" so long as you don't need to make changes.
# On the Mir website there's a lot more detail on [the gpu-2604 Snap interface](https://mir-server.io/docs/the-gpu-2604-snap-interface) and it's use.
plugs:
  gpu-2604:
    interface: content
    target: $SNAP/gpu-2604
    default-provider: mesa-2604

environment:
  # Other, generally useful environment settings...
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_DIRS:   $SNAP/usr/local/share:$SNAP/usr/share
  # XKB config
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

# The `layout` ensures that files can be found by applications where they are expected by the toolkit or application.
layout:
  # Other, generally useful paths
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /etc/fonts:
    bind: $SNAP/etc/fonts

parts:
  calculator:
    plugin: nil
    stage-packages:
      - qtbase5-examples
      - qtwayland5
      - xkb-data

  # Because Bomber won't run without a session dbus, and this isn't available to daemons on core
  # (there is no "session") we need to include a dbus session in the snap.
  # The `source: dbus` contains a script and configuration file for running `dbus-run-session`.
  dbus:
    plugin: dump
    source: dbus

  # Some utility scripts for setting up the Wayland environment
  setup:
    plugin: dump
    source: wayland-launch
    override-build: |
      # The plugs needed to run Wayland. (wayland-launch checks them, setup.sh connects them)
      # You may add further plugs here if you want these options
      PLUGS="opengl wayland gpu-2604"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/setup.sh
      craftctl default
    stage-packages:
      - inotify-tools

  gpu-2604:
    after:
      - calculator
      - dbus
      - setup
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2604-cleanup mesa-2604
      cd "$CRAFT_PRIME/usr/share/"
      rm -rf bug drirc.d glvnd libdrm lintian man \
             bash-completion dbus-1 help kconf_update kservices5 libinput locale openal pkgconfig \
             applications doc kf5 kservicetypes5 libthai metainfo perl qlogging-categories5 thumbnailers xml \
             apport config.kcfg doc-base GConf gnupg info knotifications5 kxmlgui5 libwacom themes sounds
    prime:
      - bin/gpu-2604-wrapper

platforms:
  amd64:
  armhf:
  arm64:
