#!/bin/sh
set -x

if [ "$(snapctl get daemon)" = "" ]
then
  # if no model at all, it's either classic or something is wrong
  if ! snapctl model > /dev/null || [ "$( snapctl model | awk '/^classic:/ { print $2 }' )" = "true" ]
  then snapctl set daemon=false
  else snapctl set daemon=true
  fi
fi
